/*
Deployment script for 4603E992DF4D2B664752829848AF19C8_DIO 2015\PROJECTS\MEDICALASSISTANT\MEDICALASSISTANTKAYSH\MEDICALASSISTANT\APP_DATA\DATABASE.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "4603E992DF4D2B664752829848AF19C8_DIO 2015\PROJECTS\MEDICALASSISTANT\MEDICALASSISTANTKAYSH\MEDICALASSISTANT\APP_DATA\DATABASE.MDF"
:setvar DefaultFilePrefix "4603E992DF4D2B664752829848AF19C8_DIO 2015\PROJECTS\MEDICALASSISTANT\MEDICALASSISTANTKAYSH\MEDICALASSISTANT\APP_DATA\DATABASE.MDF_"
:setvar DefaultDataPath "C:\Users\kaysh\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\kaysh\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[KeyCare$]...';


GO
CREATE TABLE [dbo].[KeyCare$] (
    [ID]                INT            IDENTITY (1, 1) NOT NULL,
    [Province]          NVARCHAR (255) NULL,
    [City]              NVARCHAR (255) NULL,
    [Suburb]            NVARCHAR (255) NULL,
    [Practice Number]   NVARCHAR (255) NULL,
    [Dr Name]           NVARCHAR (255) NULL,
    [Tel No]            NVARCHAR (255) NULL,
    [Fax No]            NVARCHAR (255) NULL,
    [Physical Address]  NVARCHAR (255) NULL,
    [Address 2]         NVARCHAR (255) NULL,
    [Address 3]         NVARCHAR (255) NULL,
    [Postal Code]       FLOAT (53)     NULL,
    [Dispensing Status] NVARCHAR (255) NULL,
    [Network No]        FLOAT (53)     NULL,
    [Description]       NVARCHAR (255) NULL,
    [Eff From]          FLOAT (53)     NULL,
    [MedName]           VARCHAR (100)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
) ON [PRIMARY];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
